routes/web.php
<?php

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\InvestorController;
use App\Http\Controllers\PartnerController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductHeadController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductGroupController;
use App\Http\Controllers\ProductSizeController;
use App\Http\Controllers\ProductTypeController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\CartsController;
use App\Http\Controllers\CustomerReturnController;
use App\Http\Controllers\InvoiceTranController;
use App\Http\Controllers\SupplierReceiveController;
use App\Http\Controllers\SupplierReturnController;
use App\Http\Controllers\GeneralExpenseController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\RegularExpenseController;
use App\Http\Controllers\TotalExpenseController;
use App\Http\Controllers\BanksController;
use App\Http\Controllers\StockOpeningEndingRecordsController;
use App\Http\Controllers\AdminController;
use App\Models\ProductCategory;
use App\Models\ProductSize;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/change/password', [App\Http\Controllers\HomeController::class, 'changePasswordUI'])->name('changePasswordUI');
Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'changePasswordConfirm'])->name('changePasswordConfirm');

Route::resource('admins',AdminController::class);
Route::post('/admins/updateAdmin/', [AdminController::class,'updateAdmin'])->name('admins.updateAdmin'); 

Route::resource('product-head',ProductHeadController::class);
Route::resource('product-category',ProductCategoryController::class);
Route::resource('product-group',ProductGroupController::class);
Route::resource('product-type',ProductTypeController::class);
Route::resource('product-size',ProductSizeController::class);
Route::resource('supplier',SupplierController::class);
Route::resource('customer',CustomerController::class);
Route::resource('product',ProductsController::class);
Route::resource('partner',PartnerController::class);
Route::post('/partner/updateMoney/', [PartnerController::class,'moneyUpdate'])->name('partner.moneyUpdate'); 
Route::get('/partnerBalance/{id}', [PartnerController::class,'balanceHistory'])->name('partner.balanceHistory');
Route::resource('expense',ExpenseController::class);
Route::resource('investor',InvestorController::class);
Route::post('/investor/updateMoney/', [InvestorController::class,'moneyUpdate'])->name('investor.moneyUpdate'); 
Route::get('/investorBalance/{id}', [InvestorController::class,'balanceHistory'])->name('investor.balanceHistory');
Route::resource('stock',StocksController::class);
Route::post('/stock/price-stock-change/{id}', [StocksController::class,'price_stock_change'])->name('stock.price_stock_change');
Route::get('/reOrderList', [StocksController::class,'reOrderList'])->name('stock.reOrderList');

Route::resource('sales',SalesController::class);
Route::post('/sales/addToCart/', [SalesController::class,'add_to_cart'])->name('sales.add_to_cart');
Route::resource('carts',CartsController::class);
Route::post('/carts/sales/checkout/', [CartsController::class,'sales_checkout'])->name('carts.sales_checkout');
Route::delete('/carts/sales/remove/', [CartsController::class,'remover_from_carts'])->name('carts.remover_from_carts');
Route::post('/carts/sales/updates/', [CartsController::class,'info_update'])->name('cart.info_update');

Route::post('/customer/info/', [CustomerController::class,'getCustomerInfoByPhoneNo'])->name('customer.getCustomerInfoByPhoneNo');
Route::post('/customer/payment/', [CustomerController::class,'payment'])->name('customer.payment');
Route::get('/customerBalance/{id}', [CustomerController::class,'balanceHistory'])->name('customer.balanceHistory');
Route::get('/customer-due-list', [CustomerController::class,'dueList'])->name('customer.dueList');

Route::post('/supplier/info/', [SupplierController::class,'getSupplierInfoByPhoneNo'])->name('supplier.getSupplierInfoByPhoneNo');
Route::post('/supplier/payment/', [SupplierController::class,'payment'])->name('supplier.payment');
Route::get('/supplierBalance/{id}', [SupplierController::class,'balanceHistory'])->name('supplier.balanceHistory');

Route::post('/product-head/editModal', [ProductHeadController::class,'modalEdit'])->name('product-head.modalEdit');
Route::post('/product/search/', [ProductsController::class,'search'])->name('product.search');
Route::get('/partners/pdf', [PartnerController::class, 'createPDF']);
Route::post('/product/details/', [ProductsController::class,'detailsByID'])->name('product.detailsByID');

Route::get('/customer-return', [CustomerReturnController::class,'index'])->name('customer_return.index');
Route::post('/customer-return/addToCart/', [CustomerReturnController::class,'add_to_cart'])->name('customer_return.add_to_cart');
Route::get('/customer-return-cart', [CustomerReturnController::class,'selectedCarts'])->name('customer_return.selectedCarts');
Route::delete('/customer-return/remove/', [CustomerReturnController::class,'remove_from_cart'])->name('customer_return.remove_from_cart');
Route::post('/carts/customer-return/updates/', [CustomerReturnController::class,'info_update'])->name('customer_return.info_update');
Route::post('/customer-return/checkout/', [CustomerReturnController::class,'sales_checkout'])->name('customer_return.sales_checkout');


Route::get('/supplier-receive', [SupplierReceiveController::class,'index'])->name('supplier_receive.index');
Route::post('/supplier-receive/addToCart/', [SupplierReceiveController::class,'add_to_cart'])->name('supplier_receive.add_to_cart');
Route::get('/supplier-receive-cart', [SupplierReceiveController::class,'selectedCarts'])->name('supplier_receive.selectedCarts');
Route::delete('/supplier-receive/remove/', [SupplierReceiveController::class,'remove_from_cart'])->name('supplier_receive.remove_from_cart');
Route::post('/carts/supplier-receive/updates/', [SupplierReceiveController::class,'info_update'])->name('supplier_receive.info_update');
Route::post('/supplier-receive/checkout/', [SupplierReceiveController::class,'buing_checkout'])->name('supplier_receive.buing_checkout');


Route::get('/supplier-return', [SupplierReturnController::class,'index'])->name('supplier_return.index');
Route::post('/supplier-return/addToCart/', [SupplierReturnController::class,'add_to_cart'])->name('supplier_return.add_to_cart');
Route::get('/supplier-return-cart', [SupplierReturnController::class,'selectedCarts'])->name('supplier_return.selectedCarts');
Route::delete('/supplier-return/remove/', [SupplierReturnController::class,'remove_from_cart'])->name('supplier_return.remove_from_cart');
Route::post('/carts/supplier-return/updates/', [SupplierReturnController::class,'info_update'])->name('supplier_return.info_update');
Route::post('/supplier-return/checkout/', [SupplierReturnController::class,'checkout'])->name('supplier_return.checkout');

Route::get('/invoice/advance-sales', [InvoiceTranController::class,'advanceSales'])->name('invoice.advance_sales_list');

Route::get('/invoice', [InvoiceTranController::class,'index'])->name('invoice.list');
Route::get('/invoice/{id}', [InvoiceTranController::class,'show'])->name('invoice.details');

Route::post('/invoice/complete', [InvoiceTranController::class,'complete_advance_sales'])->name('invoice.complete_advance_sales');
Route::post('/invoiceSearch', [InvoiceTranController::class,'invoiceSearch'])->name('invoice.invoiceSearch');
Route::get('/pdf/{id}', [InvoiceTranController::class,'generatePdf'])->name('invoice.generatePdf');



/// General Expense + Regular Expense + Total Expense
Route::resource('general-expense',GeneralExpenseController::class);
Route::resource('regular-expense',RegularExpenseController::class);
Route::post('/regular-expense/search/', [RegularExpenseController::class,'search'])->name('regular-expense.search');
Route::any('/total-expense', [TotalExpenseController::class,'index'])->name('total-expense.index');

// Account

Route::get('/journal', [JournalController::class,'journal'])->name('journal.list');
Route::get('/trial-balance', [JournalController::class,'trial_balance'])->name('journal.trial_balance');
Route::get('/income-statement', [JournalController::class,'income_statement'])->name('journal.income_statement');
Route::get('/owner-equity', [JournalController::class,'owner_equity'])->name('journal.owner_equity');
Route::get('/balance-sheet', [JournalController::class,'balance_sheet'])->name('journal.balance_sheet');
Route::any('/stock-opening-ending-reports', [StockOpeningEndingRecordsController::class,'index'])->name('stock.stock_opening_ending');



/// Bank

Route::resource('bank',BanksController::class);
Route::post('/user/name/', [BanksController::class,'getUserName'])->name('bank.getUserName');


// reports Supplier
Route::any('/reports/suppliers-date-wise-purchase', [SupplierController::class,'suppliers_date_wise_purchase'])->name('reports.date-wise-purchase');
Route::any('/reports/product-wise-sales-reports-month', [SupplierController::class,'product_wise_sales_reports_month'])->name('reports.product-wise-sales-reports-month');
Route::any('/reports/cash-flow', [JournalController::class,'cash_flow'])->name('reports.cash-flow');

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;
    protected $fillable = ['name','company_name','contact_no','address','store_id','status','created_by','created_at','updated_at'];


    public function supplierHistory()
    {
    	return $this->hasMany(SupplierBalanceHistory::class);
    }

    public function invoiceTran()
    {
    	return $this->hasMany(InvoiceTran::class);
    }

    public function banks()
    {
    	return $this->hasMany(Banks::class);
    }
}

resources/views/supplier/edit.blade.php
@extends('layouts.app')
@section('title', 'Product size')
@push('css')


@endpush

@section('content')

<!-- Main Content -->
<div class="main-content">
    <section class="section">

        <div class="col-12 section-header">
            <div class="col-6">
                <h1>Product Size</h1>
            </div>



        </div>
        @if ($errors->any())
        <div class="col-sm-12">
            <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                @foreach ($errors->all() as $error)
                <span>
                    <p>{{ $error }}</p>
                </span>
                @endforeach
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif

        @include('flash-message')

        <div class="section-body">
            <div class="col-6">
                <div class="card">
                    <div class="card-body p-0">
                        <form method="POST" action="{{route('supplier.update',$id)}}" id="editForm" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}
                            <div class=" modal-content">
                                <div class="modal-header">
                                </div>
                                <div class="modal-body">
                                    <label>Name <code>*</code></label>
                                    <input type="text" name="name" id="name" value="{{ $supplier_info->name }}" class="form-control form-control-lg" />
                                </div>

                                <div class="modal-body">
                                    <label>Phone <code>*</code></label>
                                    <input type="text" name="phone" id="phone" value="{{ $supplier_info->contact_no }}" class="form-control form-control-lg" />
                                </div>


                                <div class="modal-body">
                                    <label>Address <code></code></label>
                                    <input type="text" name="address" id="address" value="{{ $supplier_info->address }}" class="form-control form-control-lg" />
                                </div>


                                <div class="modal-body">
                                    <label>Company <code></code></label>
                                    <input type="text" name="company" id="company" value="{{ $supplier_info->company_name }}" class="form-control form-control-lg" />
                                </div>


                                <div class="modal-body">
                                    <label>Photo <code></code></label>
                                    <input type="file" name="photo" class="form-control form-control-lg" />
                                </div>

                                <input type="hidden" name="id" id="id" value="{{ $supplier_info->id }}" class="form-control form-control-lg" />
                                <div class="modal-footer bg-whitesmoke br">

                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <!-- Modal -->
    {{-- ADD Modal --}}

</div>

@endsection
@section('extra-js')

@endsection

resources/views/supplier/index.blade.php
@extends('layouts.app')
@section('title', 'Product Head')
    @push('css')


    @endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">

            <div class="col-12 section-header">
                <div class="col-6">
                    <h1>Supplier List</h1>
                </div>


                <div class="col-6 d-flex flex-row-reverse">
                    <button class="btn btn-primary" data-toggle="modal" data-target="#modal-part">
                        + Add New
                    </button>
                </div>
            </div>
            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table id="example" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Mobile No</th>
                                            <th>Company</th>
                                            <th>Adddress</th>
                                            <th>Payable</th>
                                            <th>Receivable</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($supplier_list as $key => $supplier)
                                            <tr>
                                                <td>{{ $key + 1 }}</td>
                                                <td id="t{{ $supplier->id }}">{{ $supplier->name }}</td>
                                                <td id="t{{ $supplier->id }}">{{ $supplier->contact_no }}</td>
                                                <td id="t{{ $supplier->id }}">{{ $supplier->company_name }}</td>
                                                <td id="t{{ $supplier->id }}">{{ $supplier->address }}</td>
                                                <td>{{ $supplier->payable }}</td>
                                                <td>{{ $supplier->receivable }}</td>

                                                <td>

                                                    <a class="btn btn-primary edit" href="{{ route('supplier.balanceHistory', $supplier->id) }}">Balance History</a>
                                                    <a href="{{ route('supplier.edit', $supplier->id) }}" type="button"
                                                        class="btn btn-primary edit">Edit</a>

                                                    <form method="POST"
                                                        action="{{ route('supplier.destroy', $supplier->id) }}"
                                                        style="display:inline">
                                                        {{ method_field('DELETE') }}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class=" btn-sm btn-danger"
                                                            onclick="return confirm('Confirm delete?')"><i
                                                                class="fa fa-trash-o" aria-hidden="true"></i>Delete

                                                        </button>
                                                    </form>

                                                    <a class="btn btn-primary edit"
                                                        onclick="changeModalData( '{{ $supplier }}')"
                                                        data-toggle="modal" data-target="#modal-part2">
                                                        Payable/Receivable
                                                    </a>
                                                </td>



                                            </tr>
                                        @endforeach



                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>

        <!-- Modal -->
        {{-- ADD Modal --}}
        <div class="modal fade" tabindex="-1" role="dialog" id="modal-part">
            <div class="modal-dialog" role="document">
                {{-- {{route('category.store')}} --}}
                <form method="POST" action="{{ route('supplier.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class=" modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Add supplier</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label>Name <code>*</code></label>
                                <input type="text" name="name" class="form-control form-control-lg" />
                            </div>
                            <div class="form-group">
                                <label>Phone <code>*</code></label>
                                <input type="number" name="phone" class="form-control form-control-lg" />
                            </div>
                            <div class="form-group">
                                <label>Company <code></code></label>
                                <input type="text" name="company" class="form-control form-control-lg" />
                            </div>
                            <div class="form-group">
                                <label>Address <code></code></label>
                                <input type="text" name="address" class="form-control form-control-lg" />
                            </div>
                            <!-- <div class="form-group">
                                <label>Discription <code></code></label>
                                <input type="text" name="discription" class="form-control form-control-lg" />
                            </div> -->
                            <div class="form-group">
                                <label>Photo <code></code></label>
                                <input type="file" name="photo" class="form-control form-control-lg" />
                            </div>
                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                Close
                            </button>
                            <button type="submit" class="btn btn-primary">
                                Save changes
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="modal fade" id="modal-part2" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">

                <form method="POST" action="{{ route('supplier.payment') }}">
                    {{ method_field('POST') }}
                    {{ csrf_field() }}
                    <div class=" modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Payable/Receivable</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label>Name <code></code></label>
                                <input type="text" name="supplier_name" id="supplier_name"
                                    class="form-control form-control-lg" readonly />
                            </div>
                            <div class="form-group">
                                <select id="transaction_type" name="transaction_type" class="form-control">
                                    <option value="0">Payable</option>
                                    <option value="1">Receivable</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Amount <code>*</code></label>
                                <input type="number" name="amount" id="amount" class="form-control form-control-lg" />
                            </div>
                            <input type="hidden" name="id" id="id" class="form-control form-control-lg" readonly />
                        </div>

                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                Close
                            </button>
                            <button type="submit" id="editProductHead" class="btn btn-primary">
                                Submit
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>

@endsection

@section('extra-js')
<script>
    function changeModalData(supplier) {
        console.log(supplier);

        supplier_data = JSON.parse(supplier);

        document.getElementById("id").value = supplier_data.id;
        document.getElementById("supplier_name").value = supplier_data.name;


    }
</script>

@endsection

resources/views/supplier/supplierBalanceHistory.blade.php
@extends('layouts.app')
@section('title', 'Product Head')
    @push('css')


    @endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">

            <div class="col-12 section-header">
                <div class="col-6">
                    <h1>Balance History </h1>
                    <br>
                    <h1>Name : {{ $supplier_name }}</h1>
                    <br>
                    <h1>Current Payable : {{ $supplier_payable_balance }}</h1>
                    <br>
                    <h1>Current Receivable : {{ $supplier_receivable_balance }}</h1>
                    <br>
                </div>
            </div>
            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table id="example" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Last Payable Balance</th>
                                            <th>Last Receivable Balance</th>
                                            <th>Amount</th>
                                            <th>Transaction Type</th>
                                            <th>Reason</th>
                                            <th>Updated On</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($supplier_balance_history as $key => $balance)
                                            <tr>
                                                <td>{{ $key + 1 }}</td>

                                                <td>{{ $balance->last_payable }}</td>
                                                <td>{{ $balance->last_receivable }}</td>
                                                <td>{{ $balance->amount }}</td>
                                                <td>
                                                    @if ($balance->transaction_type == 0)
                                                        Payable
                                                    @elseif($balance->transaction_type == 1)
                                                        Receivable
                                                    @endif
                                                </td>
                                                <td>{{ $balance->reason }}</td>
                                                <td>{{ \Carbon\Carbon::parse($balance->last_update)->format('d/m/Y H:i:s') }}
                                                </td>

                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>


    </div>

@endsection

@section('extra-js')
<script>
    function changeModalData(investor) {
        console.log(investor);

        investor_data = JSON.parse(investor);

        document.getElementById("id").value = investor_data.id;
        document.getElementById("current_balance").value = investor_data.balance;
        //console.log(product_obj.id);

    }
</script>
@endsection