routes/web.php
<?php

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\InvestorController;
use App\Http\Controllers\PartnerController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductHeadController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductGroupController;
use App\Http\Controllers\ProductSizeController;
use App\Http\Controllers\ProductTypeController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\CartsController;
use App\Http\Controllers\CustomerReturnController;
use App\Http\Controllers\InvoiceTranController;
use App\Http\Controllers\SupplierReceiveController;
use App\Http\Controllers\SupplierReturnController;
use App\Http\Controllers\GeneralExpenseController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\RegularExpenseController;
use App\Http\Controllers\TotalExpenseController;
use App\Http\Controllers\BanksController;
use App\Http\Controllers\StockOpeningEndingRecordsController;
use App\Http\Controllers\AdminController;
use App\Models\ProductCategory;
use App\Models\ProductSize;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/change/password', [App\Http\Controllers\HomeController::class, 'changePasswordUI'])->name('changePasswordUI');
Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'changePasswordConfirm'])->name('changePasswordConfirm');

Route::resource('admins',AdminController::class);
Route::post('/admins/updateAdmin/', [AdminController::class,'updateAdmin'])->name('admins.updateAdmin'); 

Route::resource('product-head',ProductHeadController::class);
Route::resource('product-category',ProductCategoryController::class);
Route::resource('product-group',ProductGroupController::class);
Route::resource('product-type',ProductTypeController::class);
Route::resource('product-size',ProductSizeController::class);
Route::resource('supplier',SupplierController::class);
Route::resource('customer',CustomerController::class);
Route::resource('product',ProductsController::class);
Route::resource('partner',PartnerController::class);
Route::post('/partner/updateMoney/', [PartnerController::class,'moneyUpdate'])->name('partner.moneyUpdate'); 
Route::get('/partnerBalance/{id}', [PartnerController::class,'balanceHistory'])->name('partner.balanceHistory');
Route::resource('expense',ExpenseController::class);
Route::resource('investor',InvestorController::class);
Route::post('/investor/updateMoney/', [InvestorController::class,'moneyUpdate'])->name('investor.moneyUpdate'); 
Route::get('/investorBalance/{id}', [InvestorController::class,'balanceHistory'])->name('investor.balanceHistory');
Route::resource('stock',StocksController::class);
Route::post('/stock/price-stock-change/{id}', [StocksController::class,'price_stock_change'])->name('stock.price_stock_change');
Route::get('/reOrderList', [StocksController::class,'reOrderList'])->name('stock.reOrderList');

Route::resource('sales',SalesController::class);
Route::post('/sales/addToCart/', [SalesController::class,'add_to_cart'])->name('sales.add_to_cart');
Route::resource('carts',CartsController::class);
Route::post('/carts/sales/checkout/', [CartsController::class,'sales_checkout'])->name('carts.sales_checkout');
Route::delete('/carts/sales/remove/', [CartsController::class,'remover_from_carts'])->name('carts.remover_from_carts');
Route::post('/carts/sales/updates/', [CartsController::class,'info_update'])->name('cart.info_update');

Route::post('/customer/info/', [CustomerController::class,'getCustomerInfoByPhoneNo'])->name('customer.getCustomerInfoByPhoneNo');
Route::post('/customer/payment/', [CustomerController::class,'payment'])->name('customer.payment');
Route::get('/customerBalance/{id}', [CustomerController::class,'balanceHistory'])->name('customer.balanceHistory');
Route::get('/customer-due-list', [CustomerController::class,'dueList'])->name('customer.dueList');

Route::post('/supplier/info/', [SupplierController::class,'getSupplierInfoByPhoneNo'])->name('supplier.getSupplierInfoByPhoneNo');
Route::post('/supplier/payment/', [SupplierController::class,'payment'])->name('supplier.payment');
Route::get('/supplierBalance/{id}', [SupplierController::class,'balanceHistory'])->name('supplier.balanceHistory');

Route::post('/product-head/editModal', [ProductHeadController::class,'modalEdit'])->name('product-head.modalEdit');
Route::post('/product/search/', [ProductsController::class,'search'])->name('product.search');
Route::get('/partners/pdf', [PartnerController::class, 'createPDF']);
Route::post('/product/details/', [ProductsController::class,'detailsByID'])->name('product.detailsByID');

Route::get('/customer-return', [CustomerReturnController::class,'index'])->name('customer_return.index');
Route::post('/customer-return/addToCart/', [CustomerReturnController::class,'add_to_cart'])->name('customer_return.add_to_cart');
Route::get('/customer-return-cart', [CustomerReturnController::class,'selectedCarts'])->name('customer_return.selectedCarts');
Route::delete('/customer-return/remove/', [CustomerReturnController::class,'remove_from_cart'])->name('customer_return.remove_from_cart');
Route::post('/carts/customer-return/updates/', [CustomerReturnController::class,'info_update'])->name('customer_return.info_update');
Route::post('/customer-return/checkout/', [CustomerReturnController::class,'sales_checkout'])->name('customer_return.sales_checkout');


Route::get('/supplier-receive', [SupplierReceiveController::class,'index'])->name('supplier_receive.index');
Route::post('/supplier-receive/addToCart/', [SupplierReceiveController::class,'add_to_cart'])->name('supplier_receive.add_to_cart');
Route::get('/supplier-receive-cart', [SupplierReceiveController::class,'selectedCarts'])->name('supplier_receive.selectedCarts');
Route::delete('/supplier-receive/remove/', [SupplierReceiveController::class,'remove_from_cart'])->name('supplier_receive.remove_from_cart');
Route::post('/carts/supplier-receive/updates/', [SupplierReceiveController::class,'info_update'])->name('supplier_receive.info_update');
Route::post('/supplier-receive/checkout/', [SupplierReceiveController::class,'buing_checkout'])->name('supplier_receive.buing_checkout');


Route::get('/supplier-return', [SupplierReturnController::class,'index'])->name('supplier_return.index');
Route::post('/supplier-return/addToCart/', [SupplierReturnController::class,'add_to_cart'])->name('supplier_return.add_to_cart');
Route::get('/supplier-return-cart', [SupplierReturnController::class,'selectedCarts'])->name('supplier_return.selectedCarts');
Route::delete('/supplier-return/remove/', [SupplierReturnController::class,'remove_from_cart'])->name('supplier_return.remove_from_cart');
Route::post('/carts/supplier-return/updates/', [SupplierReturnController::class,'info_update'])->name('supplier_return.info_update');
Route::post('/supplier-return/checkout/', [SupplierReturnController::class,'checkout'])->name('supplier_return.checkout');

Route::get('/invoice/advance-sales', [InvoiceTranController::class,'advanceSales'])->name('invoice.advance_sales_list');

Route::get('/invoice', [InvoiceTranController::class,'index'])->name('invoice.list');
Route::get('/invoice/{id}', [InvoiceTranController::class,'show'])->name('invoice.details');

Route::post('/invoice/complete', [InvoiceTranController::class,'complete_advance_sales'])->name('invoice.complete_advance_sales');
Route::post('/invoiceSearch', [InvoiceTranController::class,'invoiceSearch'])->name('invoice.invoiceSearch');
Route::get('/pdf/{id}', [InvoiceTranController::class,'generatePdf'])->name('invoice.generatePdf');



/// General Expense + Regular Expense + Total Expense
Route::resource('general-expense',GeneralExpenseController::class);
Route::resource('regular-expense',RegularExpenseController::class);
Route::post('/regular-expense/search/', [RegularExpenseController::class,'search'])->name('regular-expense.search');
Route::any('/total-expense', [TotalExpenseController::class,'index'])->name('total-expense.index');

// Account

Route::get('/journal', [JournalController::class,'journal'])->name('journal.list');
Route::get('/trial-balance', [JournalController::class,'trial_balance'])->name('journal.trial_balance');
Route::get('/income-statement', [JournalController::class,'income_statement'])->name('journal.income_statement');
Route::get('/owner-equity', [JournalController::class,'owner_equity'])->name('journal.owner_equity');
Route::get('/balance-sheet', [JournalController::class,'balance_sheet'])->name('journal.balance_sheet');
Route::any('/stock-opening-ending-reports', [StockOpeningEndingRecordsController::class,'index'])->name('stock.stock_opening_ending');



/// Bank

Route::resource('bank',BanksController::class);
Route::post('/user/name/', [BanksController::class,'getUserName'])->name('bank.getUserName');


// reports Supplier
Route::any('/reports/suppliers-date-wise-purchase', [SupplierController::class,'suppliers_date_wise_purchase'])->name('reports.date-wise-purchase');
Route::any('/reports/product-wise-sales-reports-month', [SupplierController::class,'product_wise_sales_reports_month'])->name('reports.product-wise-sales-reports-month');
Route::any('/reports/cash-flow', [JournalController::class,'cash_flow'])->name('reports.cash-flow');

app/Models/Banks.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banks extends Model
{
    use HasFactory;

    public function customer()
    {
    	return $this->belongsTo(Customer::class, 'customer_id');
    }

    public function supplier()
    {
    	return $this->belongsTo(Supplier::class, 'supplier_id');
    }

    public function partner()
    {
    	return $this->belongsTo(Partner::class, 'partner_id');
    }

    public function investor()
    {
    	return $this->belongsTo(Investor::class, 'investor_id');
    }
}

resources/views/banks/create.blade.php
@extends('layouts.app')
@section('title', 'Products')
    @push('css')


    @endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="col-12 section-header">
                <div class="col-6">
                    <h1> Add</h1>
                </div>

            </div>
            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">

                        <div class="card-body">
                            <form method="POST" action="{{ route('bank.store') }}" id="editForm">
                                {{ method_field('POST') }}
                                {{ csrf_field() }}

                                <div class="form-group">
                                    <label>User Type</label>
                                    <select name="user_type" id="user_type" class="form-control" onclick="getUserName()"
                                        required>
                                        <option value="0" selected="selected">Select User Type</option>
                                        <option value="Customer">Customer</option>
                                        <option value="Supplier">Supplier</option>
                                        <option value="Partner">Partner</option>
                                        <option value="Investor">Investor</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Select Name</label>
                                    <select name="user_name" id="user_name" class="form-control">
                                        <option value="0" selected="selected">Select Name</option>

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Trasaction Type</label>
                                    <select name="cash_type" class="form-control">
                                        <option value="0" selected="selected">Select Trasaction Type</option>
                                        <option value="1">Payable</option>
                                        <option value="2">Receivable</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Bank Name <code>*</code></label>
                                    <input type="text" name="bank_name" id="bank_name"
                                        class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Check No <code>*</code></label>
                                    <input type="text" name="check_no" id="check_no" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Amount <code>*</code></label>
                                    <input type="number" name="amount" id="amount" class="form-control form-control-lg" />
                                </div>
                                <div class="form-group">
                                    <label>Date <code>*</code></label>
                                    <input type="date" name="date" class="form-control form-control-lg" />
                                </div>




                                <div class="card-footer text-right">
                                    <button class="btn btn-primary mr-1" type="submit">Submit</button>

                                </div>

                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>


        <!-- End -->
    </div>



@endsection

@section('extra-js')

    <script type="text/javascript">
        function getUserName() {

            var user_type = document.getElementById("user_type").value;

            //console.log(user_type);


            $.ajax({
                url: "{{ route('bank.getUserName') }}",
                type: 'POST',
                dataType: "json",
                data: {
                    "_token": "{{ csrf_token() }}",
                    'user_type': user_type
                },

                success: function(response) {
                    //console.log("successful");
                    response = JSON.parse(response);

                    //console.log(response);

                    try {
                        if (response.isFindData == true) {

                            var len = response.data.length;
                            // console.log(len);

                            $("#user_name").empty();
                            for (var i = 0; i < len; i++) {
                                var id = response.data[i]['id'];
                                var name = response.data[i]['name'];

                                $("#user_name").append("<option value='" + id + "'>" + name + "</option>");

                            }
                        }
                    } catch (error) {

                    }

                },
                error: function(xhr, textStatus, errorThrown) {
                    // console.log("Fail");
                    // console.log(textStatus);
                    // console.log(errorThrown);
                    // console.log(xhr);
                    alert("Fail");
                }

            });

        };
    </script>

@endsection

resources/views/banks/edit.blade.php
@extends('layouts.app')
@section('title', 'Products')
    @push('css')


    @endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="col-12 section-header">
                <div class="col-6">
                    <h1> Edit</h1>
                </div>

            </div>
            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">

                        <div class="card-body">
                            <form method="POST" action="{{ route('bank.update', $id) }}" id="editForm">
                                {{ method_field('PATCH') }}
                                {{ csrf_field() }}

                                <div class="form-group">
                                    <label>User Type</label>
                                    <select name="user_type" id="user_type" class="form-control" onclick="getUserName()"
                                        required>
                                       
                                        <option value="Customer" <?php if ($bankData->user_type == "Customer") {
                                            echo 'selected';
                                        } ?> >Customer</option>
                                        <option value="Supplier" <?php if ($bankData->user_type == "Supplier") {
                                            echo 'selected';
                                        } ?> >Supplier</option>
                                        <option value="Partner" <?php if ($bankData->user_type == "Partner") {
                                            echo 'selected';
                                        } ?> >Partner</option>
                                        <option value="Investor" <?php if ($bankData->user_type == "Investor") {
                                            echo 'selected';
                                        } ?> >Investor</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Select Name</label>
                                    <select name="user_name" id="user_name" class="form-control">

                                        @if($bankData->user_type == "Customer")
                                        <option value={{ $bankData->customer_id }} selected="selected">{{ $bankData->customer->name }}</option>

                                        @elseif($bankData->user_type == "Supplier")
                                        <option value={{ $bankData->supplier_id }} selected="selected">{{ $bankData->supplier->name }}</option>

                                        @elseif($bankData->user_type == "Partner")
                                        <option value={{ $bankData->partner_id }} selected="selected">{{ $bankData->partner->name }}</option>

                                        @elseif($bankData->user_type == "Investor")
                                        <option value={{ $bankData->investor_id }} selected="selected">{{ $bankData->investor->name }}</option>

                                        @endif
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Trasaction Type</label>
                                    <select name="cash_type" class="form-control">
                                        
                                        <option value="1" <?php if ($bankData->cash_type == "1") {
                                            echo 'selected';
                                        } ?> >Payable</option>
                                        <option value="2" <?php if ($bankData->cash_type == "2") {
                                            echo 'selected';
                                        } ?>>Receivable</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Bank Name <code>*</code></label>
                                    <input type="text" name="bank_name" id="bank_name"
                                        class="form-control form-control-lg" value="{{ $bankData->bank_name }}"/>
                                </div>

                                <div class="form-group">
                                    <label>Check No <code>*</code></label>
                                    <input type="text" name="check_no" id="check_no" class="form-control form-control-lg" value="{{ $bankData->check_no }}"/>
                                </div>

                                <div class="form-group">
                                    <label>Amount <code>*</code></label>
                                    <input type="number" name="amount" id="amount" class="form-control form-control-lg" value="{{ $bankData->amount }}"/>
                                </div>
                                <div class="form-group">
                                    <label>Date <code>*</code></label>
                                    <input type="date" name="date" class="form-control form-control-lg" value="{{ $bankData->date }}"/>
                                </div>


                                <input type="hidden" name="id" id="id" value="{{ $bankData->id }}" <div class="card-footer text-right">

                                <div class="card-footer text-right">
                                    <button class="btn btn-primary mr-1" type="submit">Update</button>

                                </div>

                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>


        <!-- End -->
    </div>



@endsection

@section('extra-js')

    <script type="text/javascript">
        function getUserName() {

            var user_type = document.getElementById("user_type").value;

            //console.log(user_type);


            $.ajax({
                url: "{{ route('bank.getUserName') }}",
                type: 'POST',
                dataType: "json",
                data: {
                    "_token": "{{ csrf_token() }}",
                    'user_type': user_type
                },

                success: function(response) {
                    //console.log("successful");
                    response = JSON.parse(response);

                    //console.log(response);

                    try {
                        if (response.isFindData == true) {

                            var len = response.data.length;
                            // console.log(len);

                            $("#user_name").empty();
                            for (var i = 0; i < len; i++) {
                                var id = response.data[i]['id'];
                                var name = response.data[i]['name'];

                                $("#user_name").append("<option value='" + id + "'>" + name + "</option>");

                            }
                        }
                    } catch (error) {

                    }

                },
                error: function(xhr, textStatus, errorThrown) {
                    // console.log("Fail");
                    // console.log(textStatus);
                    // console.log(errorThrown);
                    // console.log(xhr);
                    alert("Fail");
                }

            });

        };
    </script>

@endsection

resources/views/banks/index.blade.php
@extends('layouts.app')
@section('extra-css')
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
@endsection

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">

            <div class="col-12 section-header">
                <div class="col-6">
                    <h1>Banks Data</h1>
                </div>


                <div class="col-6 d-flex flex-row-reverse">
                    <a href="{{ route('bank.create') }}" type="button" class="btn btn-primary edit">+ Add New</a>


                </div>
            </div>
            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table id="example" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>User Type</th>
                                            <th>Name</th>
                                            <th>Cash Type</th>
                                            <th>Amount</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($banksData as $key => $data)
                                            <tr>

                                                <td>{{ $key + 1 }}</td>
                                                <td>{{ $data->user_type }}</td>
                                                <td>
                                                    @if ($data->user_type == 'Customer')
                                                        {{ $data->customer->name }}
                                                    @elseif($data->user_type == "Supplier")
                                                        {{ $data->supplier->name }}

                                                    @elseif($data->user_type == "Partner")
                                                        {{ $data->partner->name }}

                                                    @elseif($data->user_type == "Investor")
                                                        {{ $data->investor->name }}
                                                    @endif
                                                </td>
                                                <td>
                                                    @if ($data->cash_type == 1)
                                                        Payable
                                                    @elseif($data->cash_type == 2)
                                                        Receivable
                                                    @endif
                                                </td>
                                                <td>{{ $data->amount }}</td>
                                                <td>{{ $data->date }}</td>

                                                <td>
                                                    <a href="{{ route('bank.show', $data->id) }}" type="button" class="btn btn-primary edit">Details</a>
                                                    {{-- <a href="{{ route('bank.edit', $data->id) }}" type="button" class="btn btn-primary edit">Edit</a>  --}}


                                            <form method="POST" action="{{ route('bank.destroy', $data->id) }}" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class=" btn-sm btn-danger" onclick="return confirm('Confirm delete?')"><i class="fa fa-trash-o" aria-hidden="true"></i>Delete

                                                </button>
                                            </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>


    </div>

@endsection


@section('extra-js')

    <script>
        $(document).ready(function() {
            $(".js-example").select2({
                width: 'resolve'
            })
        });
    </script>

@endsection